/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mdeProject.MDEProjectRuntimeModule;
import org.xtext.example.mdeProject.MDEProjectStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MDEProjectIdeSetup extends MDEProjectStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MDEProjectRuntimeModule(), new MDEProjectIdeModule()));
	}
	
}
