/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.ide;


/**
 * Use this class to register ide components.
 */
public class MDEProjectIdeModule extends AbstractMDEProjectIdeModule {
}
