/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MDEProjectUiModule extends AbstractMDEProjectUiModule {

	public MDEProjectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
