/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mdeProject.parser.antlr.internal.InternalMDEProjectParser;
import org.xtext.example.mdeProject.services.MDEProjectGrammarAccess;

public class MDEProjectParser extends AbstractAntlrParser {

	@Inject
	private MDEProjectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMDEProjectParser createParser(XtextTokenStream stream) {
		return new InternalMDEProjectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Load";
	}

	public MDEProjectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MDEProjectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
