/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MDEProjectAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/mdeProject/parser/antlr/internal/InternalMDEProject.tokens");
	}
}
