/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mdeProject.ui.internal.MdeProjectActivator;

public class MDEProjectUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdeProjectActivator.getInstance().getInjector("org.xtext.example.mdeProject.MDEProject");
	}

}
