/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MDEProjectRuntimeModule extends AbstractMDEProjectRuntimeModule {
}
