/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MDEProjectStandaloneSetup extends MDEProjectStandaloneSetupGenerated {

	public static void doSetup() {
		new MDEProjectStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
