/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mdeProject.tests

import com.google.inject.Inject
import mDE_Project.Load
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MDEProjectInjectorProvider)
class MDEProjectParsingTest {
	@Inject
	ParseHelper<Load> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
